export const registerApi = '/api/register'
export const requestOtpApi = '/api/email/request'
export const verifyOtpApi = '/api/email/verify'
export const resetPasswordApi = '/api/auth/password/reset'
export const updatePasswordApi = '/api/auth/password/update'
export const signInApi = '/api/login'
