// units
export const MILLISECONDS_IN_A_SECOND = 1000
const SECONDS_IN_A_MINUTE = 60
const NUMBER_OF_MINUTES = 15
const SECONDS_IN_A_DAY = 86400
const NUMBER_OF_DAYS = 14
// Expiry dates
export const ACCESS_TOKEN_EXPIRY_DATE_IN_SECONDS =
  SECONDS_IN_A_MINUTE * NUMBER_OF_MINUTES // 15 minutes (900 seconds)
export const REFRESH_TOKEN_EXPIRY_DATE_IN_SECONDS =
  NUMBER_OF_DAYS * SECONDS_IN_A_DAY // 14 days (1209600 seconds)
export const CRSF_TOKEN_EXPIRY_DATE_IN_SECONDS =
  REFRESH_TOKEN_EXPIRY_DATE_IN_SECONDS
