export const signUpLink = '/sign-up'
export const verifyEmailLink = '/verify-email'
export const signInLink = '/sign-in'
export const forgotPasswordLink = '/password/reset'
export const updatePasswordLink = '/password/update'
export const createProductsLink = '/dashboard/products/new'
export const dashboardLink = '/dashboard'
